// AUTO-GENERATED by scripts/generateConditionQuestions.ts
// このファイルを直接編集しないでください

import { ConditionQuestion, ConditionTag } from "../types/diagnosis";

export const CONDITION_QUESTIONS: ConditionQuestion[] = [
  {
    "id": "A",
    "question": "働く場所の希望は？",
    "options": [
      {
        "id": "A",
        "text": "家で働ける仕事が理想",
        "tag": "REMOTE_OK"
      },
      {
        "id": "B",
        "text": "状況に合わせて両立したい",
        "tag": "HYBRID_OK"
      },
      {
        "id": "C",
        "text": "在宅へのこだわりなし"
      }
    ]
  },
  {
    "id": "B",
    "question": "働き方のリズムで近いのは？",
    "options": [
      {
        "id": "A",
        "text": "短時間で無理なく働きたい",
        "tag": "SHORT_HOURS_OK"
      },
      {
        "id": "B",
        "text": "家庭の予定に合わせて柔軟に働きたい",
        "tag": "FLEXIBLE_SHIFT"
      },
      {
        "id": "C",
        "text": "しっかり働いて収入を増やしたい",
        "tag": "FULL_TIME_ORIENTED"
      }
    ]
  },
  {
    "id": "C",
    "question": "人との関わりはどれくらいがいい？",
    "options": [
      {
        "id": "A",
        "text": "できるだけ少なめ",
        "tag": "LOW_COMMUNICATION_OK"
      },
      {
        "id": "B",
        "text": "適度に協力しながら"
      },
      {
        "id": "C",
        "text": "会話や接客が好き",
        "tag": "TALK_ACTIVE"
      }
    ]
  },
  {
    "id": "D",
    "question": "体を動かす仕事・座る仕事なら？",
    "options": [
      {
        "id": "A",
        "text": "座ってする仕事がいい",
        "tag": "SITTING_WORK"
      },
      {
        "id": "B",
        "text": "どちらも少しならOK",
        "tag": "CAN_MOVE_SOMETIMES"
      },
      {
        "id": "C",
        "text": "動く方が向いている",
        "tag": "ACTIVE_WORK"
      }
    ]
  },
  {
    "id": "E",
    "question": "仕事で大切にしたいのは？",
    "options": [
      {
        "id": "A",
        "text": "無理なく続けられること",
        "tag": "LOW_STRESS"
      },
      {
        "id": "B",
        "text": "スキルが身につくこと",
        "tag": "SKILL_BUILDING"
      },
      {
        "id": "C",
        "text": "人の役に立てること",
        "tag": "HELPING_PEOPLE"
      }
    ]
  }
];

export const CONDITION_QUESTION_MAP: {
  [questionId: string]: {
    [answerId: string]: ConditionTag[];
  };
} = {
  "A": {
    "A": [
      "REMOTE_OK"
    ],
    "B": [
      "HYBRID_OK"
    ],
    "C": []
  },
  "B": {
    "A": [
      "SHORT_HOURS_OK"
    ],
    "B": [
      "FLEXIBLE_SHIFT"
    ],
    "C": [
      "FULL_TIME_ORIENTED"
    ]
  },
  "C": {
    "A": [
      "LOW_COMMUNICATION_OK"
    ],
    "B": [],
    "C": [
      "TALK_ACTIVE"
    ]
  },
  "D": {
    "A": [
      "SITTING_WORK"
    ],
    "B": [
      "CAN_MOVE_SOMETIMES"
    ],
    "C": [
      "ACTIVE_WORK"
    ]
  },
  "E": {
    "A": [
      "LOW_STRESS"
    ],
    "B": [
      "SKILL_BUILDING"
    ],
    "C": [
      "HELPING_PEOPLE"
    ]
  }
};

export function collectConditionTagsFromAnswers(
  answers: Record<string, string>
): ConditionTag[] {
  const tagSet = new Set<ConditionTag>();

  Object.entries(answers).forEach(([qIdStr, answer]) => {
    const mapForQuestion = CONDITION_QUESTION_MAP[qIdStr];
    if (!mapForQuestion) return;

    const tags = mapForQuestion[answer] ?? [];
    tags.forEach((t) => tagSet.add(t));
  });

  return Array.from(tagSet);
}
