import fs from 'fs';
import path from 'path';

// 型定義 (src/types/index.ts から抜粋・簡略化)
interface Option {
  value: string;
  label: string;
  scores: Record<string, number>; // キャラクター名 -> スコア
}

interface Question {
  id: number;
  text: string;
  options: Option[];
}

const TSV_PATH = path.resolve((process as any).cwd(), 'questions_design.tsv');
const OUTPUT_PATH = path.resolve((process as any).cwd(), 'src/data/questions.ts');

function parseTsv(content: string): Question[] {
  const lines = content.split(/\r?\n/).filter(line => line.trim() !== '');
  if (lines.length === 0) return [];

  // ヘッダー行をスキップ (質問番号, 質問文, ...)
  // データ行のみ処理
  const questionsMap = new Map<number, Question>();

  for (let i = 1; i < lines.length; i++) {
    const columns = lines[i].split('\t').map(c => c.trim());
    if (columns.length < 8) continue; // 列不足はスキップ

    const qNumStr = columns[0]; // "問1"
    const qText = columns[1];
    const optValue = columns[2]; // "A"
    const optLabel = columns[3];
    const mainChar = columns[4];
    const mainScore = parseInt(columns[5] || '0', 10);
    const subChar = columns[6];
    const subScore = parseInt(columns[7] || '0', 10);

    // 質問番号の抽出 ("問1" -> 1)
    const qIdMatch = qNumStr.match(/\d+/);
    if (!qIdMatch) continue;
    const qId = parseInt(qIdMatch[0], 10);

    // 質問オブジェクトの取得または作成
    let question = questionsMap.get(qId);
    if (!question) {
      question = {
        id: qId,
        text: qText,
        options: []
      };
      questionsMap.set(qId, question);
    }

    // スコアオブジェクトの作成
    const scores: Record<string, number> = {};
    if (mainChar) scores[mainChar] = mainScore;
    if (subChar) scores[subChar] = subScore;

    // 選択肢の追加
    question.options.push({
      value: optValue,
      label: optLabel,
      scores: scores
    });
  }

  return Array.from(questionsMap.values()).sort((a, b) => a.id - b.id);
}

function generateQuestionsTs(questions: Question[]): string {
  const questionsString = questions.map(q => {
    const optionsString = q.options.map(opt => {
      const scoresString = Object.entries(opt.scores)
        .map(([char, score]) => `        "${char}": ${score}`)
        .join(',\n');
      
      return `      {
        value: "${opt.value}",
        label: "${opt.label}",
        scores: {
${scoresString}
        }
      }`;
    }).join(',\n');

    return `  {
    id: ${q.id},
    text: "${q.text}",
    options: [
${optionsString}
    ]
  }`;
  }).join(',\n');

  return `// AUTO-GENERATED by src/data/parseQuestionsTsv.ts
import { Question } from "../types";

export const QUESTIONS: Question[] = [
${questionsString}
];
`;
}

function main() {
  if (!fs.existsSync(TSV_PATH)) {
    console.error(`❌ ${TSV_PATH} が見つかりません。`);
    (process as any).exit(1);
  }

  const tsvContent = fs.readFileSync(TSV_PATH, 'utf-8');
  const questions = parseTsv(tsvContent);

  if (questions.length === 0) {
    console.error(`❌ ${TSV_PATH} から質問データを読み取れませんでした。`);
    (process as any).exit(1);
  }

  const tsContent = generateQuestionsTs(questions);
  fs.writeFileSync(OUTPUT_PATH, tsContent, 'utf-8');
  console.log(`✅ ${OUTPUT_PATH} を生成しました。質問数: ${questions.length} 問`);
}

main();